// questions.js — Sample question bank (expand to 9,000 with your content)
// Structure: quizData[subject][levelIndex (0-29)][questionIndex (0-19)]

const quizData = {
“History”: {
1: [
{ question: “Who was the first President of the United States?”, options: [“Abraham Lincoln”, “George Washington”, “Thomas Jefferson”, “John Adams”], correct: 1 },
{ question: “In which year did World War II end?”, options: [“1943”, “1944”, “1945”, “1946”], correct: 2 },
{ question: “The Great Wall of China was primarily built to protect against which group?”, options: [“Mongols”, “Japanese”, “Romans”, “Persians”], correct: 0 },
{ question: “Which empire was ruled by Julius Caesar?”, options: [“Greek Empire”, “Ottoman Empire”, “Roman Empire”, “Byzantine Empire”], correct: 2 },
{ question: “In which year did the French Revolution begin?”, options: [“1776”, “1789”, “1799”, “1815”], correct: 1 },
{ question: “Who was the Egyptian queen famously associated with Julius Caesar and Mark Antony?”, options: [“Nefertiti”, “Cleopatra”, “Hatshepsut”, “Isis”], correct: 1 },
{ question: “Which country was the first to grant women the right to vote?”, options: [“USA”, “UK”, “New Zealand”, “France”], correct: 2 },
{ question: “The Berlin Wall fell in which year?”, options: [“1987”, “1988”, “1989”, “1991”], correct: 2 },
{ question: “Who led the Cuban Revolution?”, options: [“Che Guevara”, “Fidel Castro”, “Raul Castro”, “Batista”], correct: 1 },
{ question: “The ancient city of Carthage was located in modern-day what?”, options: [“Egypt”, “Libya”, “Tunisia”, “Algeria”], correct: 2 },
{ question: “Who was the first man to walk on the moon?”, options: [“Buzz Aldrin”, “Yuri Gagarin”, “Neil Armstrong”, “John Glenn”], correct: 2 },
{ question: “The Magna Carta was signed in which year?”, options: [“1066”, “1215”, “1492”, “1776”], correct: 1 },
{ question: “Which civilization built Machu Picchu?”, options: [“Aztec”, “Maya”, “Inca”, “Olmec”], correct: 2 },
{ question: “The Renaissance began in which country?”, options: [“France”, “Germany”, “Spain”, “Italy”], correct: 3 },
{ question: “Who was known as the ‘Iron Lady’?”, options: [“Angela Merkel”, “Margaret Thatcher”, “Indira Gandhi”, “Golda Meir”], correct: 1 },
{ question: “Which war was fought between the North and South in the USA?”, options: [“Revolutionary War”, “Civil War”, “War of 1812”, “Mexican-American War”], correct: 1 },
{ question: “The Titanic sank in which year?”, options: [“1910”, “1911”, “1912”, “1913”], correct: 2 },
{ question: “Who painted the Sistine Chapel ceiling?”, options: [“Leonardo da Vinci”, “Raphael”, “Michelangelo”, “Donatello”], correct: 2 },
{ question: “The Cold War was primarily between which two superpowers?”, options: [“USA and China”, “UK and USSR”, “USA and USSR”, “USA and Germany”], correct: 2 },
{ question: “Which explorer is credited with discovering America in 1492?”, options: [“Amerigo Vespucci”, “Vasco da Gama”, “Christopher Columbus”, “Ferdinand Magellan”], correct: 2 }
]
},
“Science”: {
1: [
{ question: “What is the chemical symbol for water?”, options: [“WA”, “H2O”, “HO2”, “W”], correct: 1 },
{ question: “How many planets are in our solar system?”, options: [“7”, “8”, “9”, “10”], correct: 1 },
{ question: “What force keeps planets in orbit around the Sun?”, options: [“Magnetism”, “Friction”, “Gravity”, “Electricity”], correct: 2 },
{ question: “What is the powerhouse of the cell?”, options: [“Nucleus”, “Ribosome”, “Mitochondria”, “Golgi Body”], correct: 2 },
{ question: “What is the speed of light approximately?”, options: [“300,000 km/s”, “150,000 km/s”, “450,000 km/s”, “100,000 km/s”], correct: 0 },
{ question: “Which gas do plants absorb during photosynthesis?”, options: [“Oxygen”, “Nitrogen”, “Carbon Dioxide”, “Hydrogen”], correct: 2 },
{ question: “What is the atomic number of Carbon?”, options: [“4”, “6”, “8”, “12”], correct: 1 },
{ question: “DNA stands for?”, options: [“Deoxyribonucleic Acid”, “Dinucleic Acid”, “Deoxyribose Acid”, “Double Nucleic Acid”], correct: 0 },
{ question: “What is the nearest star to Earth?”, options: [“Proxima Centauri”, “Sirius”, “The Sun”, “Betelgeuse”], correct: 2 },
{ question: “What is the most abundant gas in Earth’s atmosphere?”, options: [“Oxygen”, “Carbon Dioxide”, “Nitrogen”, “Argon”], correct: 2 },
{ question: “What is Newton’s first law also known as?”, options: [“Law of Gravity”, “Law of Inertia”, “Law of Motion”, “Law of Action”], correct: 1 },
{ question: “The study of fossils is called?”, options: [“Geology”, “Archaeology”, “Palaeontology”, “Biology”], correct: 2 },
{ question: “What is the hardest natural substance on Earth?”, options: [“Gold”, “Iron”, “Diamond”, “Quartz”], correct: 2 },
{ question: “How many chromosomes does a normal human cell have?”, options: [“23”, “44”, “46”, “48”], correct: 2 },
{ question: “What type of energy does the Sun primarily produce?”, options: [“Chemical”, “Nuclear”, “Mechanical”, “Electrical”], correct: 1 },
{ question: “What is the pH of pure water?”, options: [“5”, “6”, “7”, “8”], correct: 2 },
{ question: “Which organ produces insulin?”, options: [“Liver”, “Kidney”, “Pancreas”, “Stomach”], correct: 2 },
{ question: “What is the boiling point of water at sea level in Celsius?”, options: [“90°C”, “95°C”, “100°C”, “105°C”], correct: 2 },
{ question: “E = mc² was proposed by?”, options: [“Newton”, “Darwin”, “Einstein”, “Hawking”], correct: 2 },
{ question: “What is the chemical formula for table salt?”, options: [“NaCl”, “KCl”, “CaCl2”, “MgCl”], correct: 0 }
]
},
“Geography”: {
1: [
{ question: “What is the largest continent by area?”, options: [“Africa”, “North America”, “Asia”, “Europe”], correct: 2 },
{ question: “Which is the longest river in the world?”, options: [“Amazon”, “Nile”, “Yangtze”, “Mississippi”], correct: 1 },
{ question: “What is the capital of Australia?”, options: [“Sydney”, “Melbourne”, “Brisbane”, “Canberra”], correct: 3 },
{ question: “The Amazon rainforest is primarily in which country?”, options: [“Colombia”, “Venezuela”, “Brazil”, “Peru”], correct: 2 },
{ question: “What is the smallest country in the world?”, options: [“Monaco”, “San Marino”, “Vatican City”, “Liechtenstein”], correct: 2 },
{ question: “Which ocean is the largest?”, options: [“Atlantic”, “Indian”, “Arctic”, “Pacific”], correct: 3 },
{ question: “What is the capital of Japan?”, options: [“Osaka”, “Kyoto”, “Tokyo”, “Hiroshima”], correct: 2 },
{ question: “Mount Everest is in which mountain range?”, options: [“Andes”, “Alps”, “Rockies”, “Himalayas”], correct: 3 },
{ question: “Which country has the most natural lakes?”, options: [“Russia”, “USA”, “Finland”, “Canada”], correct: 3 },
{ question: “The Sahara Desert is located in which continent?”, options: [“Asia”, “Africa”, “Australia”, “South America”], correct: 1 },
{ question: “What is the capital of Brazil?”, options: [“Rio de Janeiro”, “São Paulo”, “Brasília”, “Salvador”], correct: 2 },
{ question: “Which country has the largest population?”, options: [“USA”, “India”, “China”, “Indonesia”], correct: 1 },
{ question: “The Dead Sea borders which two countries?”, options: [“Egypt and Libya”, “Israel and Jordan”, “Syria and Lebanon”, “Iraq and Iran”], correct: 1 },
{ question: “What is the capital of Canada?”, options: [“Toronto”, “Vancouver”, “Montreal”, “Ottawa”], correct: 3 },
{ question: “Which continent has no countries?”, options: [“Arctic”, “Antarctica”, “Greenland”, “Oceania”], correct: 1 },
{ question: “What is the tallest mountain in Africa?”, options: [“Mount Kenya”, “Mount Kilimanjaro”, “Ras Dashen”, “Mount Elgon”], correct: 1 },
{ question: “The Great Barrier Reef is off the coast of which country?”, options: [“New Zealand”, “Australia”, “Indonesia”, “Philippines”], correct: 1 },
{ question: “Which European country is shaped like a boot?”, options: [“Spain”, “Greece”, “Portugal”, “Italy”], correct: 3 },
{ question: “What is the capital of South Africa (administrative)?”, options: [“Cape Town”, “Durban”, “Johannesburg”, “Pretoria”], correct: 3 },
{ question: “The Panama Canal connects which two oceans?”, options: [“Pacific and Indian”, “Atlantic and Indian”, “Pacific and Atlantic”, “Arctic and Pacific”], correct: 2 }
]
},
“Maths”: {
1: [
{ question: “What is 15% of 200?”, options: [“25”, “30”, “35”, “40”], correct: 1 },
{ question: “What is the square root of 144?”, options: [“11”, “12”, “13”, “14”], correct: 1 },
{ question: “What is 7 × 8?”, options: [“54”, “56”, “58”, “64”], correct: 1 },
{ question: “What is the value of π (pi) to 2 decimal places?”, options: [“3.12”, “3.14”, “3.16”, “3.41”], correct: 1 },
{ question: “What is 2 to the power of 10?”, options: [“512”, “1024”, “2048”, “256”], correct: 1 },
{ question: “What is 1/4 as a decimal?”, options: [“0.2”, “0.25”, “0.4”, “0.5”], correct: 1 },
{ question: “What is the area of a circle with radius 5? (Use π ≈ 3.14)”, options: [“31.4”, “62.8”, “78.5”, “157”], correct: 2 },
{ question: “What is 100 ÷ 4 × 3?”, options: [“60”, “75”, “80”, “25”], correct: 1 },
{ question: “What is the next prime number after 13?”, options: [“14”, “15”, “17”, “19”], correct: 2 },
{ question: “What is 3! (3 factorial)?”, options: [“3”, “6”, “9”, “12”], correct: 1 },
{ question: “If x + 5 = 12, what is x?”, options: [“5”, “6”, “7”, “8”], correct: 2 },
{ question: “What is the sum of angles in a triangle?”, options: [“90°”, “180°”, “270°”, “360°”], correct: 1 },
{ question: “What is 0.1 + 0.2 (mathematically)?”, options: [“0.2”, “0.3”, “0.03”, “3”], correct: 1 },
{ question: “How many sides does a hexagon have?”, options: [“5”, “6”, “7”, “8”], correct: 1 },
{ question: “What is 25² (25 squared)?”, options: [“425”, “525”, “600”, “625”], correct: 3 },
{ question: “What is the median of: 3, 7, 1, 9, 5?”, options: [“3”, “5”, “7”, “9”], correct: 1 },
{ question: “What is 1000 - 387?”, options: [“613”, “623”, “633”, “643”], correct: 0 },
{ question: “A right angle is equal to how many degrees?”, options: [“45°”, “60°”, “90°”, “180°”], correct: 2 },
{ question: “What is the LCM of 4 and 6?”, options: [“6”, “12”, “18”, “24”], correct: 1 },
{ question: “What does ‘perimeter’ measure?”, options: [“Area inside a shape”, “Volume of a shape”, “Distance around a shape”, “Height of a shape”], correct: 2 }
]
},
“General Knowledge”: {
1: [
{ question: “How many colors are in a rainbow?”, options: [“5”, “6”, “7”, “8”], correct: 2 },
{ question: “What language has the most native speakers in the world?”, options: [“English”, “Spanish”, “Hindi”, “Mandarin Chinese”], correct: 3 },
{ question: “How many hours are in a week?”, options: [“148”, “168”, “172”, “196”], correct: 1 },
{ question: “Which is the largest organ in the human body?”, options: [“Liver”, “Heart”, “Brain”, “Skin”], correct: 3 },
{ question: “What does ‘USB’ stand for?”, options: [“Universal Serial Bus”, “United System Board”, “Universal System Bridge”, “Unified Serial Bus”], correct: 0 },
{ question: “How many bones are in the adult human body?”, options: [“196”, “206”, “216”, “226”], correct: 1 },
{ question: “What is the most widely spoken language in the world?”, options: [“Spanish”, “English”, “Mandarin”, “Arabic”], correct: 1 },
{ question: “Which planet is known as the Red Planet?”, options: [“Venus”, “Jupiter”, “Mars”, “Saturn”], correct: 2 },
{ question: “What is the currency of Japan?”, options: [“Yuan”, “Won”, “Yen”, “Ringgit”], correct: 2 },
{ question: “How many seconds are in an hour?”, options: [“360”, “600”, “3600”, “6000”], correct: 2 },
{ question: “What is the largest mammal in the world?”, options: [“Elephant”, “Blue Whale”, “Giraffe”, “Polar Bear”], correct: 1 },
{ question: “In which sport do you use a shuttlecock?”, options: [“Tennis”, “Squash”, “Badminton”, “Volleyball”], correct: 2 },
{ question: “What is the capital of France?”, options: [“Lyon”, “Marseille”, “Nice”, “Paris”], correct: 3 },
{ question: “How many days are in a leap year?”, options: [“364”, “365”, “366”, “367”], correct: 2 },
{ question: “Which metal is liquid at room temperature?”, options: [“Lead”, “Mercury”, “Gallium”, “Tin”], correct: 1 },
{ question: “What is the most popular sport in the world?”, options: [“Basketball”, “Cricket”, “Football (Soccer)”, “Tennis”], correct: 2 },
{ question: “How many letters are in the English alphabet?”, options: [“24”, “25”, “26”, “27”], correct: 2 },
{ question: “What does ‘GPS’ stand for?”, options: [“Global Positioning System”, “General Pathway System”, “Ground Positioning Satellite”, “Global Pathway Satellite”], correct: 0 },
{ question: “Which is the tallest animal in the world?”, options: [“Elephant”, “Camel”, “Giraffe”, “Ostrich”], correct: 2 },
{ question: “What is the chemical symbol for Gold?”, options: [“Go”, “Gd”, “Au”, “Ag”], correct: 2 }
]
},
“Philosophy”: {
1: [
{ question: “Who wrote ‘The Republic’?”, options: [“Aristotle”, “Socrates”, “Plato”, “Epicurus”], correct: 2 },
{ question: “‘Cogito, ergo sum’ (I think, therefore I am) was said by?”, options: [“Kant”, “Descartes”, “Hume”, “Leibniz”], correct: 1 },
{ question: “What is the study of knowledge called?”, options: [“Ontology”, “Epistemology”, “Axiology”, “Metaphysics”], correct: 1 },
{ question: “Which philosopher proposed the ‘categorical imperative’?”, options: [“Hume”, “Locke”, “Kant”, “Rousseau”], correct: 2 },
{ question: “Utilitarianism was developed by?”, options: [“Nietzsche”, “Bentham”, “Hegel”, “Sartre”], correct: 1 },
{ question: “What is the Socratic method primarily based on?”, options: [“Lecture”, “Reading”, “Questioning and dialogue”, “Meditation”], correct: 2 },
{ question: “Who wrote ‘Thus Spoke Zarathustra’?”, options: [“Marx”, “Nietzsche”, “Freud”, “Schopenhauer”], correct: 1 },
{ question: “Existentialism is most associated with which philosopher?”, options: [“Aristotle”, “Descartes”, “Sartre”, “Hume”], correct: 2 },
{ question: “What did Plato’s ‘Allegory of the Cave’ describe?”, options: [“A prison”, “Perception vs reality”, “Death”, “Government”], correct: 1 },
{ question: “Which school of thought says ‘virtue is knowledge’?”, options: [“Stoicism”, “Cynicism”, “Socratic philosophy”, “Epicureanism”], correct: 2 },
{ question: “Who is considered the father of modern philosophy?”, options: [“Locke”, “Descartes”, “Bacon”, “Spinoza”], correct: 1 },
{ question: “Stoicism was founded in which city?”, options: [“Rome”, “Athens”, “Alexandria”, “Sparta”], correct: 1 },
{ question: “What does ‘nihilism’ mean?”, options: [“Life has meaning”, “Nothing has meaning or purpose”, “God exists”, “Pleasure is the goal”], correct: 1 },
{ question: “Who wrote ‘Critique of Pure Reason’?”, options: [“Hegel”, “Kant”, “Hume”, “Locke”], correct: 1 },
{ question: “The ‘trolley problem’ is a famous thought experiment in?”, options: [“Logic”, “Ethics”, “Epistemology”, “Metaphysics”], correct: 1 },
{ question: “Aristotle was a student of?”, options: [“Socrates”, “Plato”, “Pythagoras”, “Heraclitus”], correct: 1 },
{ question: “Which philosopher said ‘God is dead’?”, options: [“Kierkegaard”, “Marx”, “Nietzsche”, “Schopenhauer”], correct: 2 },
{ question: “What is ‘empiricism’?”, options: [“Knowledge from reason alone”, “Knowledge from experience and senses”, “Knowledge from authority”, “Knowledge from faith”], correct: 1 },
{ question: “Confucianism originated in which country?”, options: [“Japan”, “India”, “China”, “Korea”], correct: 2 },
{ question: “Which philosopher wrote ‘Leviathan’?”, options: [“Locke”, “Rousseau”, “Hobbes”, “Voltaire”], correct: 2 }
]
},
“Chemistry”: {
1: [
{ question: “What is the atomic number of Hydrogen?”, options: [“0”, “1”, “2”, “3”], correct: 1 },
{ question: “What is the most electronegative element?”, options: [“Oxygen”, “Chlorine”, “Fluorine”, “Nitrogen”], correct: 2 },
{ question: “What type of bond involves sharing electrons?”, options: [“Ionic”, “Covalent”, “Metallic”, “Hydrogen”], correct: 1 },
{ question: “What is the pH scale range?”, options: [“0-7”, “0-10”, “0-14”, “1-14”], correct: 2 },
{ question: “What is Avogadro’s number approximately?”, options: [“6.02 × 10²²”, “6.02 × 10²³”, “6.02 × 10²⁴”, “6.02 × 10²¹”], correct: 1 },
{ question: “Which is the most abundant element in the universe?”, options: [“Helium”, “Oxygen”, “Hydrogen”, “Carbon”], correct: 2 },
{ question: “What does ‘pH’ stand for?”, options: [“Potential Hydrogen”, “Pure Hydrogen”, “Partial Hydrogen”, “Power of Hydrogen”], correct: 0 },
{ question: “What is the symbol for Iron on the periodic table?”, options: [“Ir”, “In”, “Fe”, “Fr”], correct: 2 },
{ question: “Which gas is produced in electrolysis of water at the cathode?”, options: [“Oxygen”, “Hydrogen”, “Chlorine”, “Nitrogen”], correct: 1 },
{ question: “What is an acid’s effect on litmus paper?”, options: [“Turns it blue”, “Turns it red”, “No change”, “Turns it green”], correct: 1 },
{ question: “What is the chemical formula for Glucose?”, options: [“C6H12O6”, “C6H6”, “CH4”, “C12H22O11”], correct: 0 },
{ question: “Noble gases are found in which group?”, options: [“Group 1”, “Group 7”, “Group 8/18”, “Group 4”], correct: 2 },
{ question: “What is an isotope?”, options: [“Same element, different electrons”, “Same element, different neutrons”, “Different element, same mass”, “Same element, different protons”], correct: 1 },
{ question: “What is the process of a liquid becoming a gas?”, options: [“Condensation”, “Sublimation”, “Evaporation”, “Melting”], correct: 2 },
{ question: “Which element is a liquid metal at room temperature?”, options: [“Gallium”, “Cesium”, “Mercury”, “Bromine”], correct: 2 },
{ question: “What is the chemical symbol for Silver?”, options: [“Si”, “Sv”, “Ag”, “Au”], correct: 2 },
{ question: “In organic chemistry, what does a benzene ring contain?”, options: [“6 carbon atoms”, “6 oxygen atoms”, “6 nitrogen atoms”, “6 hydrogen atoms”], correct: 0 },
{ question: “What is a catalyst?”, options: [“A substance consumed in a reaction”, “A substance that speeds up a reaction without being consumed”, “A substance that slows reactions”, “A type of acid”], correct: 1 },
{ question: “What is the molar mass of CO2?”, options: [“28 g/mol”, “40 g/mol”, “44 g/mol”, “56 g/mol”], correct: 2 },
{ question: “Photosynthesis produces which gas?”, options: [“Carbon dioxide”, “Nitrogen”, “Oxygen”, “Hydrogen”], correct: 2 }
]
},
“English”: {
1: [
{ question: “What is a synonym for ‘happy’?”, options: [“Sad”, “Joyful”, “Angry”, “Tired”], correct: 1 },
{ question: “What is an antonym for ‘ancient’?”, options: [“Old”, “Historic”, “Modern”, “Broken”], correct: 2 },
{ question: “Which sentence is grammatically correct?”, options: [“She go to school”, “She goes to school”, “She going to school”, “She gone to school”], correct: 1 },
{ question: “What is the plural of ‘mouse’?”, options: [“Mouses”, “Mice”, “Mouse”, “Mousse”], correct: 1 },
{ question: “What is a ‘metaphor’?”, options: [“A direct comparison using like or as”, “A figure of speech comparing things without like or as”, “A type of rhyme”, “An exaggeration”], correct: 1 },
{ question: “What does the prefix ‘un-’ mean?”, options: [“Again”, “Before”, “Not”, “After”], correct: 2 },
{ question: “Which is a proper noun?”, options: [“city”, “river”, “London”, “mountain”], correct: 2 },
{ question: “What tense is ‘She was running’?”, options: [“Simple past”, “Past continuous”, “Present perfect”, “Future simple”], correct: 1 },
{ question: “What is an ‘adverb’?”, options: [“Describes a noun”, “Describes a verb or adjective”, “Names a person or place”, “Shows action”], correct: 1 },
{ question: “What punctuation ends a question?”, options: [“Period (.)”, “Exclamation mark (!)”, “Question mark (?)”, “Comma (,)”], correct: 2 },
{ question: “What is the passive voice of ‘The dog bit the man’?”, options: [“The man bites the dog”, “The man was bitten by the dog”, “The dog was biting the man”, “The man bited by the dog”], correct: 1 },
{ question: “Which word is a conjunction?”, options: [“Quickly”, “Beautiful”, “And”, “Run”], correct: 2 },
{ question: “What is an ‘oxymoron’?”, options: [“A figure of speech using contradictory terms”, “A long metaphor”, “A type of alliteration”, “An exaggeration”], correct: 0 },
{ question: “Which sentence uses the Oxford comma?”, options: [“I like cats dogs and birds”, “I like cats, dogs, and birds”, “I like cats, dogs and birds”, “I like, cats, dogs, birds”], correct: 1 },
{ question: “What is ‘alliteration’?”, options: [“Rhyming at the end of lines”, “Repetition of the same consonant at the start of words”, “Using similes”, “Repeating vowel sounds”], correct: 1 },
{ question: “Which is the correct spelling?”, options: [“Accomodate”, “Acommodate”, “Accommodate”, “Acomodate”], correct: 2 },
{ question: “What is a ‘clause’?”, options: [“A type of punctuation”, “A group of words with a subject and verb”, “A synonym for paragraph”, “A type of noun”], correct: 1 },
{ question: “What does ‘verbose’ mean?”, options: [“Brief and concise”, “Using more words than needed”, “Very fast”, “Very loud”], correct: 1 },
{ question: “Which pronoun is used for objects?”, options: [“He”, “She”, “It”, “They”], correct: 2 },
{ question: “What is the superlative form of ‘good’?”, options: [“Gooder”, “Better”, “Best”, “Goodest”], correct: 2 }
]
},
“Literature”: {
1: [
{ question: “Who wrote ‘Romeo and Juliet’?”, options: [“Chaucer”, “Dickens”, “Shakespeare”, “Austen”], correct: 2 },
{ question: “In which novel does the character Jay Gatsby appear?”, options: [“Of Mice and Men”, “The Great Gatsby”, “Catcher in the Rye”, “East of Eden”], correct: 1 },
{ question: “Who wrote ‘1984’?”, options: [“Aldous Huxley”, “H.G. Wells”, “George Orwell”, “Ray Bradbury”], correct: 2 },
{ question: “What is the name of the whale in ‘Moby Dick’?”, options: [“Moby”, “The White Whale”, “Dick”, “Moby Dick”], correct: 3 },
{ question: “Who wrote ‘Pride and Prejudice’?”, options: [“Charlotte Brontë”, “Emily Brontë”, “Jane Austen”, “George Eliot”], correct: 2 },
{ question: “In ‘Harry Potter’, what is the name of the school Harry attends?”, options: [“Beauxbatons”, “Durmstrang”, “Hogwarts”, “Castelobruxo”], correct: 2 },
{ question: “Who wrote ‘The Odyssey’?”, options: [“Virgil”, “Homer”, “Ovid”, “Sophocles”], correct: 1 },
{ question: “What genre is ‘The Hobbit’?”, options: [“Science Fiction”, “Mystery”, “Fantasy”, “Historical Fiction”], correct: 2 },
{ question: “Who wrote ‘Crime and Punishment’?”, options: [“Tolstoy”, “Chekhov”, “Dostoevsky”, “Turgenev”], correct: 2 },
{ question: “What is the subtitle of ‘Frankenstein’?”, options: [“The New Adam”, “The Modern Prometheus”, “The Electric Monster”, “The Creature”], correct: 1 },
{ question: “Who wrote ‘To Kill a Mockingbird’?”, options: [“Toni Morrison”, “Harper Lee”, “Flannery O’Connor”, “Carson McCullers”], correct: 1 },
{ question: “In which Shakespeare play does the character Iago appear?”, options: [“Hamlet”, “Macbeth”, “Othello”, “King Lear”], correct: 2 },
{ question: “Who is the author of ‘Don Quixote’?”, options: [“Lorca”, “Cervantes”, “Borges”, “Neruda”], correct: 1 },
{ question: “‘Animal Farm’ is an allegory for which historical event?”, options: [“World War I”, “The French Revolution”, “The Russian Revolution”, “The Cold War”], correct: 2 },
{ question: “What is the opening line of ‘A Tale of Two Cities’ famously?”, options: [“Call me Ishmael”, “It was the best of times, it was the worst of times”, “Happy families are all alike”, “It is a truth universally acknowledged”], correct: 1 },
{ question: “Who wrote ‘The Divine Comedy’?”, options: [“Petrarch”, “Dante Alighieri”, “Boccaccio”, “Machiavelli”], correct: 1 },
{ question: “‘Lord of the Flies’ was written by?”, options: [“J.D. Salinger”, “John Steinbeck”, “William Golding”, “Ernest Hemingway”], correct: 2 },
{ question: “What is a ‘haiku’?”, options: [“A long narrative poem”, “A 3-line Japanese poem with 5-7-5 syllables”, “A type of novel”, “A rhyming couplet”], correct: 1 },
{ question: “Who wrote ‘Wuthering Heights’?”, options: [“Jane Austen”, “Emily Brontë”, “Charlotte Brontë”, “George Eliot”], correct: 1 },
{ question: “In ‘The Lord of the Rings’, who wrote the book originally?”, options: [“C.S. Lewis”, “J.K. Rowling”, “J.R.R. Tolkien”, “Terry Pratchett”], correct: 2 }
]
},
“Biology”: {
1: [
{ question: “What is the basic unit of life?”, options: [“Organ”, “Tissue”, “Cell”, “Molecule”], correct: 2 },
{ question: “What process do plants use to make food?”, options: [“Respiration”, “Photosynthesis”, “Digestion”, “Osmosis”], correct: 1 },
{ question: “How many chambers does the human heart have?”, options: [“2”, “3”, “4”, “5”], correct: 2 },
{ question: “What is the function of red blood cells?”, options: [“Fight infection”, “Carry oxygen”, “Clot blood”, “Produce hormones”], correct: 1 },
{ question: “DNA is found in which part of the cell?”, options: [“Mitochondria”, “Cytoplasm”, “Nucleus”, “Ribosome”], correct: 2 },
{ question: “What is mitosis?”, options: [“Cell death”, “Cell division producing 2 identical cells”, “Sexual reproduction”, “Cell growth”], correct: 1 },
{ question: “Which organ filters blood in the human body?”, options: [“Liver”, “Heart”, “Lungs”, “Kidneys”], correct: 3 },
{ question: “What is the largest organ in the body?”, options: [“Liver”, “Heart”, “Skin”, “Brain”], correct: 2 },
{ question: “Which blood type is the universal donor?”, options: [“A”, “B”, “AB”, “O”], correct: 3 },
{ question: “What is the process by which cells use oxygen to produce energy?”, options: [“Photosynthesis”, “Fermentation”, “Cellular Respiration”, “Osmosis”], correct: 2 },
{ question: “What are the building blocks of proteins?”, options: [“Fatty acids”, “Amino acids”, “Nucleotides”, “Glucose”], correct: 1 },
{ question: “Which part of the brain controls balance?”, options: [“Cerebrum”, “Cerebellum”, “Brainstem”, “Hippocampus”], correct: 1 },
{ question: “What is the role of ribosomes?”, options: [“Energy production”, “Protein synthesis”, “DNA replication”, “Lipid storage”], correct: 1 },
{ question: “What is osmosis?”, options: [“Movement of solute across membrane”, “Movement of water across semi-permeable membrane”, “Active transport of ions”, “Cell division”], correct: 1 },
{ question: “What is the scientific study of fungi called?”, options: [“Botany”, “Zoology”, “Mycology”, “Ecology”], correct: 2 },
{ question: “Which vitamin is produced when skin is exposed to sunlight?”, options: [“Vitamin A”, “Vitamin B12”, “Vitamin C”, “Vitamin D”], correct: 3 },
{ question: “What is the human body’s largest internal organ?”, options: [“Heart”, “Liver”, “Lungs”, “Intestines”], correct: 1 },
{ question: “Insulin is produced by which organ?”, options: [“Liver”, “Kidney”, “Pancreas”, “Stomach”], correct: 2 },
{ question: “What is ‘natural selection’?”, options: [“Humans choosing animals to breed”, “Survival of fittest organisms that reproduce”, “Random mutation only”, “Artificial breeding”], correct: 1 },
{ question: “What do white blood cells do?”, options: [“Carry oxygen”, “Clot blood”, “Fight infection”, “Produce energy”], correct: 2 }
]
},
“Physics”: {
1: [
{ question: “What is the unit of force?”, options: [“Joule”, “Watt”, “Newton”, “Pascal”], correct: 2 },
{ question: “What is the speed of sound in air approximately?”, options: [“300 m/s”, “343 m/s”, “400 m/s”, “500 m/s”], correct: 1 },
{ question: “What type of energy does a moving object have?”, options: [“Potential”, “Thermal”, “Kinetic”, “Chemical”], correct: 2 },
{ question: “What is Ohm’s Law?”, options: [“V = IR”, “P = IV”, “F = ma”, “E = mc²”], correct: 0 },
{ question: “Which colour has the longest wavelength in visible light?”, options: [“Violet”, “Blue”, “Green”, “Red”], correct: 3 },
{ question: “What is the unit of electric current?”, options: [“Volt”, “Ohm”, “Watt”, “Ampere”], correct: 3 },
{ question: “What does a thermometer measure?”, options: [“Pressure”, “Temperature”, “Humidity”, “Speed”], correct: 1 },
{ question: “What is absolute zero in Celsius?”, options: [”-100°C”, “-200°C”, “-273°C”, “-300°C”], correct: 2 },
{ question: “What is the law of conservation of energy?”, options: [“Energy can be created”, “Energy can be destroyed”, “Energy cannot be created or destroyed”, “Energy is always lost as heat”], correct: 2 },
{ question: “What is the formula for kinetic energy?”, options: [“KE = mv”, “KE = ½mv²”, “KE = mgh”, “KE = F×d”], correct: 1 },
{ question: “What particle has a positive charge?”, options: [“Electron”, “Neutron”, “Proton”, “Photon”], correct: 2 },
{ question: “What is refraction?”, options: [“Light bouncing off a surface”, “Light bending as it passes through a medium”, “Light being absorbed”, “Light splitting into colours”], correct: 1 },
{ question: “What is the gravitational acceleration on Earth?”, options: [“8.9 m/s²”, “9.8 m/s²”, “10.8 m/s²”, “11 m/s²”], correct: 1 },
{ question: “What does a convex lens do to light?”, options: [“Diverges it”, “Converges it”, “Absorbs it”, “Reflects it”], correct: 1 },
{ question: “What is the unit of power?”, options: [“Joule”, “Newton”, “Watt”, “Pascal”], correct: 2 },
{ question: “What is an electrical insulator?”, options: [“Copper”, “Silver”, “Rubber”, “Aluminium”], correct: 2 },
{ question: “What type of wave is sound?”, options: [“Transverse”, “Electromagnetic”, “Longitudinal”, “Light”], correct: 2 },
{ question: “What is the Doppler effect?”, options: [“Change in wave frequency due to motion”, “Wave bending around objects”, “Wave reflection”, “Wave absorption”], correct: 0 },
{ question: “What keeps electrons in orbit around the nucleus?”, options: [“Gravity”, “Strong nuclear force”, “Electromagnetic force”, “Weak nuclear force”], correct: 2 },
{ question: “What is work done equal to?”, options: [“mass × velocity”, “force × distance”, “mass × acceleration”, “force × time”], correct: 1 }
]
},
“Fun Facts”: {
1: [
{ question: “A group of flamingos is called a?”, options: [“Flock”, “Herd”, “Flamboyance”, “Colony”], correct: 2 },
{ question: “Honey never spoils. Edible honey was found in Egyptian tombs how many years old?”, options: [“1,000”, “2,000”, “3,000”, “5,000”], correct: 2 },
{ question: “What is the only fruit with seeds on the outside?”, options: [“Raspberry”, “Kiwi”, “Strawberry”, “Pomegranate”], correct: 2 },
{ question: “A day on Venus is longer than a year on Venus. Why?”, options: [“It orbits fast”, “It rotates very slowly”, “It has no atmosphere”, “It is too close to the Sun”], correct: 1 },
{ question: “Which animal can sleep while standing up?”, options: [“Cat”, “Dog”, “Horse”, “Bear”], correct: 2 },
{ question: “Octopuses have how many hearts?”, options: [“1”, “2”, “3”, “4”], correct: 2 },
{ question: “The word ‘nerd’ was first used in which Dr. Seuss book?”, options: [“Cat in the Hat”, “If I Ran the Zoo”, “Green Eggs and Ham”, “The Lorax”], correct: 1 },
{ question: “Which is the only mammal capable of true flight?”, options: [“Flying squirrel”, “Bat”, “Flying lemur”, “Sugar glider”], correct: 1 },
{ question: “Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid. Is this true?”, options: [“False”, “True”, “Uncertain”, “Only partly”], correct: 1 },
{ question: “How many hearts does an earthworm have?”, options: [“0”, “1”, “5”, “10”], correct: 2 },
{ question: “Bananas are technically classified as what?”, options: [“Fruit”, “Berry”, “Vegetable”, “Nut”], correct: 1 },
{ question: “Which country consumes the most chocolate per capita?”, options: [“USA”, “Belgium”, “Switzerland”, “Germany”], correct: 2 },
{ question: “How long is a goldfish’s memory span actually?”, options: [“3 seconds”, “A few seconds”, “Several months”, “Only a minute”], correct: 2 },
{ question: “The inventor of the World Wide Web is?”, options: [“Bill Gates”, “Steve Jobs”, “Tim Berners-Lee”, “Mark Zuckerberg”], correct: 2 },
{ question: “What is the most common element in Earth’s crust?”, options: [“Iron”, “Silicon”, “Oxygen”, “Aluminium”], correct: 2 },
{ question: “Which animal has the highest blood pressure?”, options: [“Elephant”, “Giraffe”, “Blue Whale”, “Cheetah”], correct: 1 },
{ question: “How many muscles does it take to smile?”, options: [“5”, “12”, “17”, “43”], correct: 2 },
{ question: “Which country invented pizza?”, options: [“USA”, “Greece”, “Italy”, “France”], correct: 2 },
{ question: “What colour is a polar bear’s fur actually?”, options: [“White”, “Yellow”, “Transparent/Clear”, “Light grey”], correct: 2 },
{ question: “The shortest war in history lasted how long?”, options: [“38 minutes”, “1 hour”, “6 hours”, “1 day”], correct: 0 }
]
},
“Movies”: {
1: [
{ question: “Which film won the first ever Academy Award for Best Picture?”, options: [“Ben-Hur”, “Wings”, “Gone with the Wind”, “It Happened One Night”], correct: 1 },
{ question: “Who directed ‘Schindler’s List’?”, options: [“Martin Scorsese”, “Francis Ford Coppola”, “Steven Spielberg”, “Stanley Kubrick”], correct: 2 },
{ question: “Which movie features the quote ‘I’ll be back’?”, options: [“Predator”, “Total Recall”, “The Terminator”, “Commando”], correct: 2 },
{ question: “What is the highest-grossing film of all time (unadjusted for inflation)?”, options: [“Avengers: Endgame”, “Titanic”, “Avatar”, “Star Wars”], correct: 2 },
{ question: “In ‘The Lion King’, what is Simba’s father’s name?”, options: [“Rafiki”, “Scar”, “Mufasa”, “Zazu”], correct: 2 },
{ question: “Who played Iron Man in the Marvel Cinematic Universe?”, options: [“Chris Evans”, “Chris Hemsworth”, “Robert Downey Jr.”, “Mark Ruffalo”], correct: 2 },
{ question: “What year was the original ‘Star Wars’ released?”, options: [“1975”, “1977”, “1979”, “1980”], correct: 1 },
{ question: “Which film featured the song ‘My Heart Will Go On’?”, options: [“Ghost”, “Dirty Dancing”, “Titanic”, “Pretty Woman”], correct: 2 },
{ question: “Who directed ‘Inception’?”, options: [“Ridley Scott”, “Christopher Nolan”, “James Cameron”, “Denis Villeneuve”], correct: 1 },
{ question: “What was the first Pixar full-length animated film?”, options: [“A Bug’s Life”, “Toy Story”, “Finding Nemo”, “Monsters Inc”], correct: 1 },
{ question: “In ‘The Silence of the Lambs’, what is Hannibal Lecter’s profession?”, options: [“Lawyer”, “Surgeon”, “Psychiatrist”, “Professor”], correct: 2 },
{ question: “Which actress played Katniss Everdeen in ‘The Hunger Games’?”, options: [“Shailene Woodley”, “Emma Watson”, “Jennifer Lawrence”, “Emma Stone”], correct: 2 },
{ question: “Who played the Joker in ‘The Dark Knight’?”, options: [“Jack Nicholson”, “Jared Leto”, “Joaquin Phoenix”, “Heath Ledger”], correct: 3 },
{ question: “Which film is set in the fictional African nation of Wakanda?”, options: [“Black Panther”, “The Avengers”, “Captain America”, “Thor”], correct: 0 },
{ question: “What is the name of the toy cowboy in ‘Toy Story’?”, options: [“Buzz”, “Woody”, “Rex”, “Slinky”], correct: 1 },
{ question: “Who directed ‘Pulp Fiction’?”, options: [“Joel Coen”, “Tim Burton”, “Quentin Tarantino”, “David Fincher”], correct: 2 },
{ question: “‘Here’s looking at you, kid’ is from which film?”, options: [“Gone with the Wind”, “Casablanca”, “Citizen Kane”, “The Maltese Falcon”], correct: 1 },
{ question: “Which film features a character named Forrest Gump?”, options: [“Cast Away”, “Philadelphia”, “Forrest Gump”, “The Green Mile”], correct: 2 },
{ question: “What is the name of Batman’s butler?”, options: [“James”, “Alfred”, “Edward”, “Thomas”], correct: 1 },
{ question: “Which actress has won the most Academy Awards?”, options: [“Meryl Streep”, “Katharine Hepburn”, “Cate Blanchett”, “Bette Davis”], correct: 1 }
]
},
“Sports”: {
1: [
{ question: “How many players are on a standard football (soccer) team?”, options: [“9”, “10”, “11”, “12”], correct: 2 },
{ question: “In which country did the Olympic Games originate?”, options: [“Italy”, “Egypt”, “Greece”, “Turkey”], correct: 2 },
{ question: “How many Grand Slam tournaments are there in tennis?”, options: [“2”, “3”, “4”, “5”], correct: 2 },
{ question: “What is the maximum score in ten-pin bowling per game?”, options: [“200”, “250”, “300”, “350”], correct: 2 },
{ question: “Which country has won the most FIFA World Cups?”, options: [“Germany”, “Argentina”, “Italy”, “Brazil”], correct: 3 },
{ question: “How many rings are on the Olympic flag?”, options: [“4”, “5”, “6”, “7”], correct: 1 },
{ question: “In basketball, how many points is a free throw worth?”, options: [“1”, “2”, “3”, “4”], correct: 0 },
{ question: “What sport is played at Wimbledon?”, options: [“Cricket”, “Golf”, “Tennis”, “Squash”], correct: 2 },
{ question: “How many holes are in a standard round of golf?”, options: [“9”, “12”, “18”, “21”], correct: 2 },
{ question: “What is the national sport of Japan?”, options: [“Judo”, “Karate”, “Sumo”, “Kendo”], correct: 2 },
{ question: “In cricket, how many balls are in a standard over?”, options: [“4”, “5”, “6”, “8”], correct: 2 },
{ question: “Which American city has an NFL team called the Eagles?”, options: [“Chicago”, “Atlanta”, “Philadelphia”, “Denver”], correct: 2 },
{ question: “What is the diameter of a basketball hoop in inches?”, options: [“14”, “16”, “18”, “20”], correct: 2 },
{ question: “In boxing, how long is a standard round?”, options: [“2 minutes”, “3 minutes”, “4 minutes”, “5 minutes”], correct: 1 },
{ question: “Which country invented rugby?”, options: [“Australia”, “New Zealand”, “South Africa”, “England”], correct: 3 },
{ question: “How many players are on a baseball team on the field?”, options: [“8”, “9”, “10”, “11”], correct: 1 },
{ question: “What colour flag is waved in Formula 1 to end the race?”, options: [“Red”, “Yellow”, “White”, “Chequered”], correct: 3 },
{ question: “Which swimmer has won the most Olympic gold medals of all time?”, options: [“Ian Thorpe”, “Mark Spitz”, “Michael Phelps”, “Ryan Lochte”], correct: 2 },
{ question: “What is the term for three consecutive strikes in bowling?”, options: [“Triple”, “Hat trick”, “Turkey”, “Strike out”], correct: 2 },
{ question: “In volleyball, how many players are on each side?”, options: [“5”, “6”, “7”, “8”], correct: 1 }
]
},
“Music”: {
1: [
{ question: “How many strings does a standard guitar have?”, options: [“4”, “5”, “6”, “7”], correct: 2 },
{ question: “Which band was Michael Jackson a part of before going solo?”, options: [“The Beatles”, “The Jackson 5”, “Boyz II Men”, “The Temptations”], correct: 1 },
{ question: “What does ‘forte’ mean in music?”, options: [“Slow”, “Soft”, “Loud”, “Fast”], correct: 2 },
{ question: “Which composer wrote ‘Für Elise’?”, options: [“Mozart”, “Bach”, “Beethoven”, “Chopin”], correct: 2 },
{ question: “How many notes are in a musical octave?”, options: [“6”, “7”, “8”, “12”], correct: 2 },
{ question: “Which country does reggae music originate from?”, options: [“Cuba”, “Trinidad”, “Jamaica”, “Haiti”], correct: 2 },
{ question: “What is the lowest male singing voice called?”, options: [“Tenor”, “Baritone”, “Bass”, “Contralto”], correct: 2 },
{ question: “Who is known as the ‘King of Pop’?”, options: [“Prince”, “Elvis Presley”, “Michael Jackson”, “David Bowie”], correct: 2 },
{ question: “Which instrument has 88 keys?”, options: [“Organ”, “Piano”, “Harpsichord”, “Accordion”], correct: 1 },
{ question: “What is the time signature of a waltz?”, options: [“2/4”, “4/4”, “3/4”, “6/8”], correct: 2 },
{ question: “Which band wrote ‘Bohemian Rhapsody’?”, options: [“Led Zeppelin”, “The Rolling Stones”, “Queen”, “The Who”], correct: 2 },
{ question: “What does ‘a cappella’ mean?”, options: [“With instruments”, “Singing without instruments”, “Very slowly”, “With a choir”], correct: 1 },
{ question: “Jazz music originated in which US city?”, options: [“Chicago”, “New York”, “Los Angeles”, “New Orleans”], correct: 3 },
{ question: “How many symphonies did Beethoven compose?”, options: [“7”, “8”, “9”, “10”], correct: 2 },
{ question: “What is the fastest tempo marking in music?”, options: [“Allegro”, “Vivace”, “Presto”, “Prestissimo”], correct: 3 },
{ question: “Which artist released ‘Thriller’ in 1982?”, options: [“Prince”, “Michael Jackson”, “David Bowie”, “Lionel Richie”], correct: 1 },
{ question: “What is a ‘riff’ in music?”, options: [“A type of drum beat”, “A repeated chord progression or melody”, “A musical key change”, “A type of singing style”], correct: 1 },
{ question: “What family of instruments does the violin belong to?”, options: [“Woodwind”, “Brass”, “Percussion”, “String”], correct: 3 },
{ question: “The opera ‘La Traviata’ was composed by?”, options: [“Puccini”, “Verdi”, “Mozart”, “Wagner”], correct: 1 },
{ question: “What does ‘BPM’ stand for in music?”, options: [“Beats Per Minute”, “Bass Per Measure”, “Beats Per Measure”, “Base Per Minute”], correct: 0 }
]
},
“Technology”: {
1: [
{ question: “What does ‘CPU’ stand for?”, options: [“Central Processing Unit”, “Computer Processing Utility”, “Central Program Unit”, “Core Processing Unit”], correct: 0 },
{ question: “What does ‘HTML’ stand for?”, options: [“HyperText Markup Language”, “High Text Markup Language”, “HyperText Modern Language”, “Hyper Transfer Markup Language”], correct: 0 },
{ question: “Who co-founded Apple with Steve Jobs?”, options: [“Bill Gates”, “Steve Wozniak”, “Jony Ive”, “Tim Cook”], correct: 1 },
{ question: “What does ‘URL’ stand for?”, options: [“Uniform Resource Locator”, “Universal Resource Link”, “Uniform Retrieval Language”, “United Resource Location”], correct: 0 },
{ question: “What programming language was created by Guido van Rossum?”, options: [“Java”, “Ruby”, “Python”, “Perl”], correct: 2 },
{ question: “What is the full form of ‘AI’?”, options: [“Advanced Intelligence”, “Artificial Intelligence”, “Automated Intelligence”, “Autonomous Interface”], correct: 1 },
{ question: “What does ‘RAM’ stand for?”, options: [“Read Access Memory”, “Random Access Memory”, “Rapid Access Module”, “Read And Modify”], correct: 1 },
{ question: “Which company developed the Android operating system?”, options: [“Apple”, “Microsoft”, “Google”, “Samsung”], correct: 2 },
{ question: “What is a ‘byte’ composed of?”, options: [“4 bits”, “6 bits”, “8 bits”, “16 bits”], correct: 2 },
{ question: “Which programming language is primarily used for web styling?”, options: [“HTML”, “JavaScript”, “CSS”, “PHP”], correct: 2 },
{ question: “Who founded Microsoft?”, options: [“Steve Jobs”, “Mark Zuckerberg”, “Jeff Bezos”, “Bill Gates”], correct: 3 },
{ question: “What does ‘VPN’ stand for?”, options: [“Virtual Private Network”, “Virtual Protocol Node”, “Verified Private Network”, “Virtual Personal Node”], correct: 0 },
{ question: “What is ‘open source’ software?”, options: [“Software that costs money”, “Software with publicly available source code”, “Software by Microsoft”, “Software with no bugs”], correct: 1 },
{ question: “Which company makes the iPhone?”, options: [“Samsung”, “Google”, “Apple”, “Sony”], correct: 2 },
{ question: “What does ‘IoT’ stand for?”, options: [“Internet of Technology”, “Interface of Things”, “Internet of Things”, “Integration of Technology”], correct: 2 },
{ question: “What is the binary representation of the number 5?”, options: [“100”, “101”, “110”, “111”], correct: 1 },
{ question: “What is ‘cloud computing’?”, options: [“Computing done in the sky”, “Storing and accessing data over the internet”, “Using solar energy for computers”, “Wireless computing”], correct: 1 },
{ question: “Which social media platform was launched in 2004?”, options: [“Twitter”, “Instagram”, “Facebook”, “LinkedIn”], correct: 2 },
{ question: “What does ‘SSL’ stand for in web security?”, options: [“Secure Server Link”, “Secure Sockets Layer”, “Standard Security Layer”, “Safe Socket Link”], correct: 1 },
{ question: “What is ‘machine learning’?”, options: [“Robots learning to walk”, “AI systems learning from data”, “Computer hardware training”, “Manual data entry”], correct: 1 }
]
}
};
